sudo: false
language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.cache"

deploy:
    provider: script
    script: "cp .travis.maven-settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
        tags: true

notifications:
    email:
        recipients:
        - android.bruns@googlemail.com
        on_success: change
        on_failure: always